Feature mulitpath integration
AP-Sensing/os-tester pull request #11
Opened 2024-07-19 12:05 UTC by Braincrushy

Added paths to the stages so mutliple ways are possible

2024-07-19 12:05 UTC, Braincrushy commented
TODO make working images? 0_1.png is missing
everything else should work normaly

2024-07-24 07:13 UTC, COM8 requested changes
Thanks for contributing! Only a few minor changes required and then we are ready to go.

2024-07-24 07:13 UTC, COM8 commented on src/os_tester/stages.py
> +    def __load_stages(self,yamlFileName: str) -> None:
```suggestion
    def __load_stages(self, yamlFileName: str) -> None:
```

2024-07-24 07:13 UTC, COM8 commented on src/os_tester/stages.py
> +        ymlFilePath: str = path.join(self.basePath,yamlFileName+".yml")
```suggestion
        ymlFilePath: str = path.join(self.basePath, yamlFileName + ".yml")
```

2024-07-24 07:13 UTC, COM8 commented on src/os_tester/stages.py
> +    A single stage with the timeout
```suggestion
    A single stage with timeout.
```

2024-07-24 07:13 UTC, COM8 commented on src/os_tester/stages.py
> +class subpath:
```suggestion
class subPath:
```

Please use lowerCamelCase for class names.

2024-08-02 07:29 UTC, COM8 approved these changes

2024-08-02 07:29 UTC, merged